name: FuseICL-maniskill

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.11
  - numpy=1.26
  - pytorch=2.1
  - pytorch-cuda=11.8
  - libgl=1.7
  - pip
  - pip:
      - mani-skill==3.0.1
